[project]
name = "evaluation-lumo"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.2.1",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.4",
    "sphinx>=8.1.3",
]
